volumes:
  prometheus-data:
  socket:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./qsys/static:/etc/nginx/static
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/nginx/html:/usr/share/nginx/html
      - ./services/nginx/log:/var/log/nginx
      - ./services/socket:/var/run/uwsgi
    restart: unless-stopped
    depends_on:
      - django

  django:
    build: ./qsys/
    volumes:
      - ./qsys/:/app
      - ./services/socket:/var/run/uwsgi

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./services/prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana
    user: root
    volumes:
      - ./services/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
