# Generated by Django 4.2.2 on 2023-07-07 08:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctfanswerhistory",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.ctfteam",
            ),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator("^[a-zA-Z0-9 ]+$"),
                ],
            ),
        ),
    ]
