# Generated by Django 4.2.2 on 2023-07-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_ctfscore_ctf"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctfscore",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.ctfteam",
            ),
        ),
    ]
