# Generated by Django 4.2.2 on 2023-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_ctfinformation_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctfinformation",
            name="is_active",
            field=models.BooleanField(default=False, help_text="CTF実施状況"),
        ),
    ]
