# Generated by Django 4.2.2 on 2023-07-07 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_ctfinformation_paticipants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ctfinformation",
            name="paticipants",
        ),
    ]
