# Generated by Django 4.2.2 on 2023-07-07 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_ctfinformation_paticipants"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctfinformation",
            name="participants",
            field=models.ManyToManyField(
                blank=True, help_text="参加者", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
