# Generated by Django 4.2.2 on 2023-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_ctfinformation_show_player_ranking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
