# Generated by Django 4.2.3 on 2023-08-02 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_ctfinformation_is_paused"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ctfinformation",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="ctfinformation",
            name="questions",
        ),
        migrations.RemoveField(
            model_name="ctfquestion",
            name="category",
        ),
        migrations.RemoveField(
            model_name="ctfquestion",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="ctfscore",
            name="ctf",
        ),
        migrations.RemoveField(
            model_name="ctfscore",
            name="question",
        ),
        migrations.RemoveField(
            model_name="ctfscore",
            name="team",
        ),
        migrations.RemoveField(
            model_name="ctfscore",
            name="user",
        ),
        migrations.DeleteModel(
            name="CtfAnswerHistory",
        ),
        migrations.DeleteModel(
            name="CtfInformation",
        ),
        migrations.DeleteModel(
            name="CtfQuestion",
        ),
        migrations.DeleteModel(
            name="CtfQuestionCategory",
        ),
        migrations.DeleteModel(
            name="CtfQuestionDifficulty",
        ),
        migrations.DeleteModel(
            name="CtfScore",
        ),
    ]
