# Generated by Django 4.2.3 on 2023-08-02 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_remove_ctfinformation_participants_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="team",
        ),
        migrations.DeleteModel(
            name="CtfTeam",
        ),
    ]
